name: myob-CI-pipeline

on:
  push:

jobs:
  build-and-unit-test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build docker image
        run: make build SECRET= ${{ secrets.SECRET_KEY}}

      - name: unit test
        run: make test
